# Generated by Django 3.2.25 on 2025-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbuild',
            name='build_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
